knowledge:
  - path: go.mod
    kind: dependencies
  - path: kinds/main.go
    kind: implementations
  - path: config/main.go
    kind: implementations
  - path: knowledge/main.go
    kind: implementations