knowledge:
  - path: ../../prompts/prompt.md.tmpl
    kind: implementations
  - path: ../../prompts/oneMoreMake/main.go
    kind: implementations
  - path: ../../prompts/oneMoreMake/prompt.md.tmpl
    kind: implementations
  - path: ../../domain/model/chat/main.go
    kind: implementations
  - path: ../../domain/model/chat/claude/main.go
    kind: implementations
  - path: ../../domain/external/claude/main.go
    kind: implementations
  - path: ../../domain/model/chat/openAi/main.go
    kind: implementations
  - path: ../../domain/external/openAi/main.go
    kind: implementations
  - path: ../../domain/repository/config/main.go
    kind: implementations
  - path: ../../domain/repository/file/main.go
    kind: implementations
  - path: ../../domain/service/configFindService/main.go
    kind: implementations
  - path: ../../domain/service/knowledgeLoad/main.go
    kind: implementations
  - path: ../../domain/service/knowledgeScan/main.go
    kind: implementations