knowledge:
  - path: ../../prompts/prompt.md.tmpl
    kind: implementations
  - path: ../../prompts/oneMoreMake/main.go
    kind: implementations
  - path: ../../prompts/oneMoreMake/prompt.md.tmpl
    kind: implementations
  - path: ../../domain/model/chat/claude/main.go
    kind: implementations
  - path: ../../domain/external/claude/main.go
    kind: implementations
  - path: ../../infrastructure/external/claude/main.go
    kind: implementations